name_list = {
    "姜璐": "jianglu",
    "范红明": "fanhongming",
    "宋平": "songping",
    "杨雪莹": "yangxueying800522",
    "周佳霖": "zhoujialin",
    "宋雅洁":"songyajie",
    "赵红远": "zhaohongyuan",
    "李俊琦": "lijunqi",
    "钱亚松": "qianyasong",
    "李静文": "lijingwen801960",
    "周美文": "zhoumeiwen",
    "胡孟鋆": "humengyun802635",
    "岑美静": "cenmeijing",
    "王晶晶": "wangjingjing600075",
    "吴恙": "wuyang802598",
    "王怡舒": "wangyishu",
    "刘丕": "liupi",
    "何文": "hewen601619",
    "崔晶晶": "cuijingjing",
    "闫旭": "yanxu800417",
    "张玄月": "zhangxuanyue",
    "张海旭": "zhanghaixu",
    "刘嘉琪": "liujiaqi801693",
    "李伟静":"liweijing",
    "顾雪菲": "guxuefei",
    "刘晋宁": "liujinning801032",
    "张丽华": "zhanglihua"
}